danceworkout/webapp/api_1_0/__init__.py
from flask import Blueprint
api = Blueprint('api', __name__)
from . import machines  # noqa
from . import ivtdoc  # noqa

danceworkout/webapp/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views  # noqa

danceworkout/webapp/main/views.py
from flask import render_template
from flask import current_app as cap
from . import main
# ______________________________


@main.route('/', methods=['GET'])
@main.route('/home', methods=['GET'])
def home():
    return render_template(
        "main/home.html",
        config=cap.config,
    )
# ______________________________


@main.route('/contact', methods=['GET'])
def contact():
    return render_template(
        "main/contact.html",
        config=cap.config,
    )
# ______________________________


@main.route('/details', methods=['GET'])
def details():
    return render_template(
        "main/details.html",
        config=cap.config,
    )
# ______________________________

danceworkout/webapp/templates/layout.html
<!DOCTYPE html>
<html dir="rtl" lang="he-IL">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>עיצוב גוף בריקוד</title>
        <meta name="keywords" content=" ריקוד עיצוב אימון כושר ריקודי בטן סלסה חוג אימון לנשים">
        <meta name="description" content="
            להתחיל שנה חדשה בתחביב חדש
            כי גם לאמא מגיע חוג
            רקדת בילדות? מעולה! אצלינו תמצאי מסגרת לשימור ושיפור היכולות.
            לא רקדת אף פעם? אל דאגה, אפשר להתחיל עכשיו!
            אימונים בקבוצות קטנות עם יחס אישי.
        ">

        <meta property="og:locale" content="he_IL" />
        <meta property="og:type" content="article" />
        <meta property="og:title" content="Dance Workout"/>
        <meta property="og:title" content="עיצוב גוף בריקוד" />

        <meta property="og:description" content="
            להתחיל שנה חדשה בתחביב חדש!
            כי גם לאמא מגיע חוג
            רקדת בילדות? מעולה! אצלינו תמצאי מסגרת לשימור ושיפור היכולות.
            לא רקדת אף פעם? אל דאגה, אפשר להתחיל עכשיו!
            אימונים בקבוצות קטנות עם יחס אישי.
        "/>

        <meta property="og:url" content="http://www.danceworkout.co.il" />
        <meta property="article:author" content="https://www.facebook.com/public/Marina-Ziv" />
        <meta property="article:tag" content="עיצוב" />
        <meta property="article:tag" content="אימון" />
        <meta property="article:tag" content="כושר" />
        <meta property="article:tag" content="ריקודי בטן" />
        <meta property="article:tag" content="סלסה" />
        <meta property="article:tag" content="חוג" />
        <meta property="article:tag" content="אימון לנשים" />
        <meta property="article:tag" content="טנגו" />

        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico', r=82845) }}" type="image/x-icon">
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico', r=82845) }}" type="image/x-icon">

        <link rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" 
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <link rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" 
        integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">

        {% block head %}{% endblock %}
    </head>

    <body>
        <div id="wrap">
            <div class="page-container">

                <div id="menu-container" class="container danceworkout">
                    <nav class="navbar navbar-default">

                        <div class="container-fluid">

                            <div class="navbar-header">

                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar5">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>

                                <a class="navbar-brand" href="/home">
                                    <span class="address_key">עיצוב גוף בריקוד</span>
                                    <img class="logo_img" src=/static/images/matnasd-logo.jpg alt="Dance Workout Logo">
                                </a>


                            </div>

                            <div id="navbar5" class="navbar-collapse collapse">
                                <ul class="nav navbar-nav navbar-right">

                                    <li id="nav-contact">
                                        <a href="{{ url_for('main.contact') }}">
                                            ליצירת קשר <span class="glyphicon glyphicon-phone-alt"></span>
                                        </a>
                                    </li>

                                    <li id="nav-details">
                                        <a href="{{ url_for('main.details') }}">
                                             מה עושים בשיעור <span class="glyphicon glyphicon-question-sign"></span>
                                        </a>
                                    </li>

                                    <li id="nav-home">
                                        <a href="{{ url_for('main.home') }}">
                                             בית <span class="glyphicon glyphicon-home"></span>
                                        </a>
                                    </li>

                                </ul>
                            </div>
                            <!--/.nav-collapse -->

                        </div>
                        <!--/.container-fluid -->
                    </nav>
                </div>

                <div class="container page-content">

                        {% block main_content %}
                        {% endblock %}
                    
                </div><!-- /.container -->
            </div><!-- /.page-container -->
        </div><!-- /#wrap -->

        <div id="footer">
            <div class="container">
                <p class="text-muted credit"> &copy; מרינה זיו 2017</p>
            </div>
        </div>


        <script language="javascript" src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script language="javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
        <script 
        src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

        <script>

            jQuery(document).ready(function () {
                {% block docready %}{% endblock %} 
            });

        </script>

    </body>
</html>